
[[redirects]]
  from = "/api/proxy/voiceagent/*"
  to = "https://delicate-bavarois-995263.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/proxy/voiceagent"
  to = "https://delicate-bavarois-995263.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/learningpath/*"
  to = "https://delicate-bavarois-995263.netlify.app/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
